import pickle
import gspread
from google.auth.transport.requests import Request

SHEET_ID = "1J6yx5qZO05dDkmSiC-IvOXleqU4tL2GTqUu0b0idTxE"

CLIENTS = [
    {"Client Name": "Asset Thread", "Website URL": "https://assetthread.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Asset Thread", "Primary Contact": "Sanket", "Contact Email": "sanket.uchil@sensystechnologies.com", "Contract Start": "", "Assigned Team Member": "Chintan Nalekar", "Notes": "CC: sfm@sensysindia.com, nilesh@thirdslash.com | From: reporting@thirdslash.com | Posts/month: 2 | Niche: Fixed Asset Tracking Software"},
    {"Client Name": "HRM Thread", "Website URL": "https://hrmthread.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "HRM Thread", "Primary Contact": "Sanket", "Contact Email": "sanket.uchil@sensystechnologies.com", "Contract Start": "", "Assigned Team Member": "Chintan Nalekar", "Notes": "CC: sfm@sensysindia.com, nilesh@thirdslash.com | From: reporting@thirdslash.com | Posts/month: 4 | Niche: HR Software Payroll"},
    {"Client Name": "Lancers CBSE", "Website URL": "https://lancers.edu.in", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Lancers CBSE", "Primary Contact": "Angad", "Contact Email": "angad@estrela-inc.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: keshav@estrelaglobalventures.com, nilesh@thirdslash.com, ashish@estrela-inc.com | From: reporting@thirdslash.com | Posts/month: 2 | Niche: CBSE School"},
    {"Client Name": "Lancers GSEB", "Website URL": "https://lancers.edu.in/gseb", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Lancers GSEB", "Primary Contact": "Angad", "Contact Email": "angad@estrela-inc.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: keshav@estrelaglobalventures.com, nilesh@thirdslash.com, ashish@estrela-inc.com | From: reporting@thirdslash.com | Posts/month: 2 | Niche: GSEB School"},
    {"Client Name": "Lancers Early Years", "Website URL": "https://lancers.edu.in/early-years", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Lancers Early Years", "Primary Contact": "Angad", "Contact Email": "angad@estrela-inc.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: keshav@estrelaglobalventures.com, nilesh@thirdslash.com, ashish@estrela-inc.com | From: reporting@thirdslash.com | Posts/month: 2 | Niche: Preschool Education"},
    {"Client Name": "Lancers Army School", "Website URL": "https://lancers.edu.in/army-school", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Lancers Army School", "Primary Contact": "Angad", "Contact Email": "angad@estrela-inc.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: keshav@estrelaglobalventures.com, nilesh@thirdslash.com, ashish@estrela-inc.com | From: reporting@thirdslash.com | Posts/month: 2 | Niche: Group of Schools Surat"},
    {"Client Name": "mPokket", "Website URL": "https://mpokket.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "10", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora, Medium", "New Pages This Month": "No", "PowerSuite Project Name": "mPokket", "Primary Contact": "Moumita", "Contact Email": "shekhar.suman@mpokket.com", "Contract Start": "", "Assigned Team Member": "Chintan Nalekar", "Notes": "CC: gopinath.srikrishna@mpokket.com, nilesh@thirdslash.com | From: reporting@thirdslash.com | Posts/month: 30 | Niche: Instant Loan App"},
    {"Client Name": "Potential Engineering", "Website URL": "https://potentialengineering.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Potential Engineering", "Primary Contact": "Deepam", "Contact Email": "deepamsheth@potentialengineering.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: sandhyanair@potentialengineering.com | From: reporting@thirdslash.com | Posts/month: 6 | Niche: Water Pollutant Removal"},
    {"Client Name": "EZ Lifestyle", "Website URL": "https://ezlifestyle.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "EZ Lifestyle", "Primary Contact": "Tom", "Contact Email": "tgreenberg@trilliumsalesgroup.com", "Contract Start": "", "Assigned Team Member": "Chintan Nalekar", "Notes": "CC: nilesh@thirdslash.com | From: reporting@thirdslash.com | Posts/month: 4 | Niche: Hangover Prevention Pills"},
    {"Client Name": "Estrela Hotels", "Website URL": "https://estrelahotels.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "Yes", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Estrela Hotels", "Primary Contact": "Angad", "Contact Email": "angad@estrela-inc.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: ashish@estrela-inc.com, sales@estrelahotels.co | From: reporting@thirdslash.com | Posts/month: 4 | Niche: Luxury Beach Resort"},
    {"Client Name": "Kelly Powers", "Website URL": "https://kellypowers.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Kelly Powers", "Primary Contact": "Kelly", "Contact Email": "kelly@kellypowers.com", "Contract Start": "", "Assigned Team Member": "Chintan Nalekar", "Notes": "CC: nilesh@thirdslash.com | From: reporting@thirdslash.com | Posts/month: 4 | Niche: Nutrition Coach Dietitian"},
    {"Client Name": "HappyLyfe", "Website URL": "https://happylyfe.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "HappyLyfe", "Primary Contact": "Venus", "Contact Email": "aphrrdt@gmail.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: mrinal.mike@happylyfe.co, nilesh@thirdslash.com | From: reporting@thirdslash.com | Posts/month: 4 | Niche: Organic CBD Products Thailand"},
    {"Client Name": "Public69", "Website URL": "https://public69.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "No", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "10", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Public69", "Primary Contact": "Rari", "Contact Email": "nirarid@gmail.com", "Contract Start": "", "Assigned Team Member": "Chintan Nalekar", "Notes": "CC: nilesh@thirdslash.com | From: reporting@thirdslash.com | Posts/month: 10 | Niche: Escort Service UK"},
    {"Client Name": "Ovation Square", "Website URL": "https://ovationsquare.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "Yes", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Ovation Square", "Primary Contact": "Luca", "Contact Email": "luca@piovragroup.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: nilesh@thirdslash.com | From: marketing@piovragroup.com | Posts/month: 8 | Niche: Corporate Wedding Event Venues Long Beach"},
    {"Client Name": "Piovra Group", "Website URL": "https://piovragroup.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "Yes", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Piovra Group", "Primary Contact": "Luca", "Contact Email": "luca@piovragroup.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: nilesh@thirdslash.com | From: marketing@piovragroup.com | Posts/month: 4 | Niche: Event Space Rental Los Angeles"},
    {"Client Name": "Brickroom LA", "Website URL": "https://brickroomla.com", "Google Drive Folder": "", "GitHub Dashboard": "", "GSC Connected": "Yes", "GA4 Connected": "Yes", "GMB Connected": "Yes", "Blog: Who Writes": "ThirdSlash", "Blog: Who Publishes": "ThirdSlash", "Content Approval": "Yes", "On-Page Audits/Month": "2", "Citation Links/Month": "5", "Guest Posting": "No", "Tech Audit Cycle": "Every 2 Months", "Platforms (Reddit/Quora/Medium)": "Reddit, Quora", "New Pages This Month": "No", "PowerSuite Project Name": "Brickroom LA", "Primary Contact": "Luca", "Contact Email": "luca@piovragroup.com", "Contract Start": "", "Assigned Team Member": "Himanshu Pawar", "Notes": "CC: nilesh@thirdslash.com | From: marketing@piovragroup.com | Posts/month: 4 | Niche: Venue Booking Los Angeles"},
]

HEADERS = ["Client Name","Website URL","Google Drive Folder","GitHub Dashboard","GSC Connected","GA4 Connected","GMB Connected","Blog: Who Writes","Blog: Who Publishes","Content Approval","On-Page Audits/Month","Citation Links/Month","Guest Posting","Tech Audit Cycle","Platforms (Reddit/Quora/Medium)","New Pages This Month","PowerSuite Project Name","Primary Contact","Contact Email","Contract Start","Assigned Team Member","Notes"]

def get_credentials():
    with open('token.pickle', 'rb') as token:
        creds = pickle.load(token)
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    return creds

def update_client_profiles():
    creds = get_credentials()
    gc = gspread.authorize(creds)
    sh = gc.open_by_key(SHEET_ID)
    ws = sh.worksheet("01_Client Profile")
    all_values = ws.get_all_values()
    last_row = len(all_values)
    if last_row > 3:
        ws.delete_rows(4, last_row)
    rows_to_add = [[c.get(h, "") for h in HEADERS] for c in CLIENTS]
    ws.append_rows(rows_to_add)
    print(f"Done. {len(CLIENTS)} clients written to 01_Client Profile.")
    for c in CLIENTS:
        print(f"  + {c['Client Name']} | {c['Assigned Team Member']}")

update_client_profiles()
